import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { getSortedTupleData, getFilteredTupleIds } from '../lib/tuple'
import { config } from '../lib/config'
// import Date from '../components/date'

export async function getStaticProps() {
  const allTupleData = await getSortedTupleData()
  const filteredTupleIds = await getFilteredTupleIds()
  // console.log('allTupleData: ', allTupleData)
  // console.log('filteredTupleIds: ', filteredTupleIds)
  return {
    props: {
      allTupleData,
      filteredTupleIds
    }
  }
}

export default function Home({ allTupleData, filteredTupleIds }) {
  // console.log('allTupleData: ', JSON.stringify(allTupleData))
  // console.log('filteredTupleIds: ', filteredTupleIds)
  return (
    <div className={styles.container}>
      <Head>
        <title>IOT DHT22/21</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to IOT!
        </h1>

        <div className={styles.grid}>
          {allTupleData.map((tuple) => (
            <Link key={`/tuple/${tuple.id}`} href={`/tuple/${tuple.id}/${config.filter.none}/${config.filter.none}`} className={styles.card}>
              <div>
                <a>{tuple.date}</a>&nbsp;
              </div>
            </Link>
          ))}
        </div>
      </main>

      {/* list all possible paths - debug purpose only
      <div>
        <ul>
          {filteredTupleIds.map((tuple) => {
            // console.log(tuple.params.id)
            return (
            <Link key={`${tuple.params.id}_${tuple.params.esp}_${tuple.params.gpio}`} href={`/tuple/${tuple.params.id}/${tuple.params.esp}/${tuple.params.gpio}`} className={styles.card}>
              <div>
                <a>{`/tuple/${tuple.params.id}/${tuple.params.esp}/${tuple.params.gpio}`}</a>&nbsp;
              </div>
            </Link>
          )})}
        </ul>
      </div>
      */}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
