name: daily-cron
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://test-next-dht22-bqn9ipy53-doodeck.vercel.app/api/params' \
          --header 'Authorization: Bearer ${{ secrets.MY_TEST_SECRET }}'
